-- CreateTable
CREATE TABLE "Pose" (
    "poseId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "videoLink" STRING NOT NULL,
    "steps" STRING[],
    "repeat" INT4 NOT NULL,

    CONSTRAINT "Pose_pkey" PRIMARY KEY ("poseId")
);
